server:
  port: 8006
spring:
  application:
    name: cloud-provider-hystrixpayment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
